URL_1 = "htpps://bonigarcia.dev/selenium-webdriver-java/data-types.html"
first_name = "Иван"
last_name = "Петров"
address = "Ленина, 55-3"
email = "test@scypro.com"
phone = "+7985899998787"
zip_code = ""
city = "Москва"
country = "Росссия"
job_position = "QA"
company = "ScyPro"

URL_2 = "https://bonigarcia.dev/selenium-webdriver-java/slow-calculator.html"

URL_3 = "https://www.saucedemo.com/"